config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get 'home/index'
  devise_for :users

  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  before_save :default_values
  validates :name, :presence => {message: "Task name can't be blank"}

  enum priority: [ :higher, :medium, :lower ]

  private
  def default_values
    self.finished ||= false
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :default_values
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todos, :dependent => :delete_all

  validates :username, :presence => {message: "Username can't be blank"}
  validates :username, :uniqueness => {message: "Username already in use. Please choose another"}

  enum admin: [:false, :true]

  private
  def default_values
    self.admin ||= false
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  self.responder = ActionController::Responder

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :username, :first_name, :last_name, :admin) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :current_password, :password, :password_confirmation, :username, :first_name, :last_name, :admin) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.admin.to_s == "true"
        @todo_list = Todo.all.order(:priority)
      else
        @todo_list = Todo.where(:user_id => current_user.id).order(:priority)
      end
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    if current_user.admin.to_s == "true"
      @todos = Todo.all.order(:priority)
    else
      @todos = Todo.where(:user_id => current_user.id).order(:priority)
    end
  end

  def new
    @todo = Todo.new(user_id: current_user.id)
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Task #{@todo.name} successfuly created!"
      redirect_to todos_url
    else
      render action: "new"
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(get_id_from_params)

    respond_to do |format|
      if @todo.update_attributes(todo_params)
        flash[:notice] = "Task #{@todo.name} successfuly updated!"
        format.html {redirect_to todos_url}
        format.json {render :json => @todo, status: :ok}
      else
        format.html {render action: "edit"}
        format.json {render :json => @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo = Todo.find(get_id_from_params)
    @todo.destroy

    respond_to do |format|
      flash[:notice] = "Task deleted!"
      format.html {render action: "index"}
      format.json {render :json => @todo, status: :ok}
    end
  end

  private
  def get_id_from_params
    params[:id].to_i != 0 ? params[:id] : params[:todo][:id]
  end

  def todo_params
    params.require(:todo).permit(
      :name, :user_id, :finished, :priority
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_options.html.erb
<div class="span1">
	<%=button_to 'Edit', edit_todo_path(todo1), :method => :get, :class=>"btn-mini btn-info"%>
</div>
<div class="spam1">
	<button class="btn-mini btn-danger" onClick="destroyTodo(<%=todo1.id%>, this)">Delete</button>
</div>

app/views/home/_todos.html.erb
<div class="row" style="border: solid 1px white;">
	<div class="span2">
		<b> <%= todo.name %> </b>
	</div>
	<div class="span2">
		Created by: <b><%= todo.user.username %></b>
	</div>
	<div class="span2">
		Priority: <b><%= todo.priority %></b>
	</div>
	<div class="span1">
		<label class="checkbox">
			<%= check_box_tag("finished", todo.finished?, todo.finished?, onclick: "todoDone(#{todo.id}, #{todo.finished?})")%> Finished
		</label>
	</div>
	<%if todo.user.id == current_user.id || current_user.admin.to_s == 'true'%>
		<%= render partial: "options", locals: {todo1: todo}%>
	<%end%>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<div class="container">
		<div class="hero-unit span10 pagination-centered">
			<h1>Hello, <%= current_user.username %> </h1>
			<p>This is your personal To-Do List.</p>
			<p><a href="todos/new" class="btn btn-primary btn-large">New Task</a></p>
		</div>
	</div>
	<br>
	<div class="container">
		<div class="hero-unit span10 pagination-centered">
			<% if @todo_list.blank? %>
				<p>You have nothing to do.</p>
			<% else %>

				<ul id="sortable" class='nav nav-tabs nav-stacked'>
					<% @todo_list.each do |todo| %>
						<li>
							<%= render partial: "todos", locals: {todo: todo} %>
						</li>
					<% end %>
				</ul>
			<% end %>
			</div>
		</div>
<%else%>
	<div class="hero-unit span12 pagination-centered">
		<h1>Hello! </h1>
		<p>Sing up to create your personal To-Do List, and see who needs help.</p>
		<p><a href="users/sign_up" class="btn btn-primary btn-large">Sing up</a></p>
	</div>
<%end%>
<script>
$(function() {
  $( "#sortable" ).sortable();
  $( "#sortable" ).disableSelection();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>ToDoList</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/">To-Do List</a>
			<div class="nav-collapse navbar-responsive-collapse collapse" style="height: 0px;">
				<ul class="nav">
						<% if user_signed_in? %>
							<li class="active"><a href="/todos">To-Do</a></li>
							<li class="divider-vertical"></li>
							<li><a><%= current_user.username %></a></li>
							<li class="divider-vertical"></li>
							<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
							<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
						<% else %>
							<li class="divider-vertical"></li>
							<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
							<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
						<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
  <% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/todos/_options.html.erb
<div class="span1">
	<%=button_to 'Edit', edit_todo_path(todo1), :method => :get, :class=>"btn-mini btn-info"%>
</div>
<div class="spam1">
	<button class="btn-mini btn-danger" onClick="destroyTodo(<%=todo1.id%>, this)">Delete</button>
</div>

app/views/todos/_todos.html.erb
<div class="row" style="border: solid 1px white;">
	<div class="span2">
		<b> <%= todo.name %> </b>
	</div>
	<div class="span2">
		Created by: <b><%= todo.user.username %></b>
	</div>
	<div class="span2">
		Priority: <b><%= todo.priority %></b>
	</div>
	<div class="span2">
		<label class="checkbox">
			<%= check_box_tag("finished", todo.finished?, todo.finished?, onclick: "todoDone(#{todo.id}, #{todo.finished?})")%> Finished
		</label>
	</div>
	<%if todo.user.id == current_user.id || current_user.admin.to_s == 'true'%>
		<%= render partial: "options", locals: {todo1: todo}%>
	<%end%>
</div>

app/views/todos/edit.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-6'>
			<%= simple_form_for @todo do |f| %>
				<% f.error_notification %>
				<div class="form-inputs">
					<%= f.input :name, required: true, autofocus: true %>
					<%= f.input :priority, include_hidden: false,
								 collection: [ ['Higher', :higher], ['Medium', :medium], ['Lower', :lower] ] %>
				</div>

				<div class="form-actions">
					<%= f.button :submit, "Save" %>
				</div>
			<%end%>
		</div>
	</div>
</div>

app/views/todos/index.html.erb
<div class='container'>
	<div class="side-nav-container affix-top">
		<p><a href="todos/new" class="btn btn-primary btn-small">New Task</a></p>
		<% if @todos.blank? %>
			<p>You have nothing to do.</p>
		<% else %>
			<ul id="sortable" class='nav nav-tabs nav-stacked'>
				<% @todos.each do |todo| %>
					<li>
						<%= render partial: "todos", locals: {todo: todo} %>
					</li>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>
<script>
$(function() {
  $( "#sortable" ).sortable();
  $( "#sortable" ).disableSelection();
});
</script>

app/views/todos/new.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-6'>
			<%= simple_form_for @todo do |f| %>
				<% f.error_notification %>
				<div class="form-inputs">
					<%= f.input :user_id,  :as => :hidden, :input_html => { :value => "#{current_user.id}" }%>
					<%= f.input :name, required: true, autofocus: true %>
					<%= f.input :priority, :include_hidden => false, :selected => [:higher],
								 collection: [ ['Higher', :higher], ['Medium', :medium], ['Lower', :lower]	] %>
				</div>

				<div class="form-actions">
					<%= f.button :submit, "Save" %>
				</div>
			<%end%>
		</div>
	</div>
</div>